### PR TITLE
Adding fesh2

### PR DESCRIPTION
**Pull request by jejl**
Hi Dave and Ed,

Here's the new version of fesh. I've put it in fs/fesh2 and the README.md describes how to use it. I've set it up with Python setuptools and setup.py should manage the installation correctly. Comments etc are welcome! 

Cheers,
Jim

### CODE REVIEW

**Comment by jejl** [comment]
A couple of bug fixes.

**Comment by dehorsley** [comment]
Thanks, Jim, I'll try to do some testing and make a few notes later in the week. One comment first though: I'd like to develop a style convention in FS source. What would you think about running it through a formatter? I'm open to other options, as we haven't committed to anything yet for python, but I suggest [black](https://github.com/psf/black). It's opinionated, i.e. doesn't have configuration, and the results look good to my eye. 

I set it up to run when I save the file; I think most editors nowadays have this option.

**Comment by jejl** [comment]
Hi Dave,
Sure, no problem, all set up.

**Comment by dehorsley** [comment]
Thanks, could you push the formatted code :)

**Comment by jejl** [comment]
Done.

**Pull request closed without merging**
