### PR TITLE
Add a patch to the nng source and modify CPPFLAGS for FSL8.

### PR DESCRIPTION
**Pull request by jfhquick**
This PR applies a patch file to the nng-1.3.0 tarball as it unpacks it and otherwise removes the two CPPFLAGS that are inappropriate for FSL8 (Lenny).  With this added even the tip of master compiles cleanly on FSL8.

### CODE REVIEW

**Review by wehimwich — APPROVED** [review]
It looks complete to me, but I am hardly an expert on nng.

I verified that it makes and the server runs on Lenny, Wheezy, and Stretch, but no testing beyond that.

**Comment by jfhquick** [comment]
I have changed track completely.  By selecting the posix_pollq_poll variant nng-.3.0 compiles on Lenny.  The CPPFLAGS changes are still included as those reflect real system header file differences.

**Comment by wehimwich** [comment]
Compile and run checked on FSL8 (_Lenny_), FSL9 (_Wheezy_), and FSL10 (_Stretch_).
Relative paths allow compile with _/usr2/fs_ link not defined was checked.
Justing waiting to hear from @dehorsley for other advice and/or if anything else should be checked before squashing and merging.

**Review by wehimwich — APPROVED** [review]

**Comment by dehorsley** [comment]
Nice work Jon!

One thought: maybe this should be kept in line with the code (gen_nng.make and nng.make.template) that generates the unofficial Makefile from the cmake build system for when we update the vendored nng verson. Maybe it's an easy manual edit, but some reminder might be useful.

I guess we're loosing a bit of performance dropping epoll for poll on systems where epoll could be used, but nng isn't really on a performance critical path so that's fine.

**Pull request merged**
